"use client";

import type { CatalogEvent } from "../../automation-types";
import { resolveProcessIconGlyph } from "../shell/home-presentation";
import { RunStatusBadge, formatDateTime, type RunRecord } from "../operations/OperationsApprovalsScreens";

export type IntegrationMode = "demo" | "live" | "cached" | "unconfigured";
export type CatalogChange = { id: string; title: string; kind: "new" | "changed" | "removed" };
export type CatalogMeta = { syncedAt: string | null; source: "demo" | "xyops" | "cache" | "none"; stale: boolean; changes: CatalogChange[] };
export type AutomationSection = { category: string; slug: string; count: number; events: number; workflows: number; order: number };

function Status({ children, tone = "success" }: { children: React.ReactNode; tone?: string }) {
  return <span className={`status ${tone}`}>{children}</span>;
}

export function AutomationCatalog({ items, sections, selectedCategory, mode, meta, error, loading, recentRuns, canRun, canManageSettings, onCategoryChange, onSync, onOpenSettings, onLaunch }: { items: CatalogEvent[]; sections: AutomationSection[]; selectedCategory: string; mode: IntegrationMode; meta: CatalogMeta; error: string; loading: boolean; recentRuns: RunRecord[]; canRun: boolean; canManageSettings: boolean; onCategoryChange: (category: string) => void; onSync: () => void; onOpenSettings: () => void; onLaunch: (event: CatalogEvent) => void }) {
  const categories = sections.length;
  const visibleItems = selectedCategory === "all" ? items : items.filter((event) => event.category === selectedCategory);
  const activeSection = sections.find((section) => section.category === selectedCategory) ?? null;
  const changeMap = new Map(meta.changes.map((change) => [change.id, change.kind]));
  return <div className="content-stack automation-page">
    <section className="automation-hero"><div><span className="eyebrow">XYOPS AUTOMATION PORTAL</span><h2>{activeSection ? activeSection.category : "Портал автоматизаций"}</h2><p>{activeSection ? `Автоматически созданный раздел: ${activeSection.events} Events и ${activeSection.workflows} Workflows. Поля форм и правила запуска получены из XYOps.` : "Разделы, маршруты, карточки и формы создаются из метаданных Events и Workflows. XYOps остаётся оркестратором, а портал предоставляет пользовательский интерфейс и визуализацию."}</p>{activeSection && <code className="generated-route">/automation/{activeSection.slug}</code>}</div><div>{!canRun && <Status tone="neutral">Только просмотр</Status>}<button className="secondary" disabled={loading} onClick={onSync}>{loading ? "Синхронизация…" : "⟳ Обновить каталог"}</button></div></section>
    <section className={`catalog-sync ${meta.stale || error ? "stale" : ""}`}><span className={`source-dot ${mode}`} /><div><strong>{error ? "Ошибка загрузки каталога XYOps" : meta.source === "xyops" ? "Каталог синхронизирован с XYOps" : meta.source === "cache" ? "Показан сохранённый снимок" : meta.source === "demo" ? "Демонстрационный каталог" : "XYOps не настроен"}</strong><small>{error || (meta.syncedAt ? `Последняя успешная синхронизация: ${new Date(meta.syncedAt).toLocaleString("ru-RU")}` : "Снимок каталога ещё не создан")}</small></div>{meta.changes.length > 0 && <Status tone="violet">{meta.changes.filter((change) => change.kind === "new").length} новых · {meta.changes.filter((change) => change.kind === "changed").length} изменено · {meta.changes.filter((change) => change.kind === "removed").length} удалено</Status>}{(meta.stale || error) && <Status tone="warning">Требуется проверка</Status>}</section>
    <section className="catalog-summary"><article><span>⌘</span><div><strong>{items.length}</strong><small>доступных процессов</small></div></article><article><span>▦</span><div><strong>{categories}</strong><small>категорий</small></div></article><article><span>◇</span><div><strong>{items.reduce((sum, event) => sum + event.fields.length, 0)}</strong><small>динамических полей</small></div></article><article><span className={`source-dot ${mode}`} /><div><strong>{mode === "live" ? "LIVE" : mode === "cached" ? "CACHE" : mode === "demo" ? "DEMO" : "OFF"}</strong><small>источник каталога</small></div></article></section>
    <div className="category-tabs"><button className={selectedCategory === "all" ? "active" : ""} onClick={() => onCategoryChange("all")}>Все процессы <b>{items.length}</b></button>{sections.map((section) => <button className={selectedCategory === section.category ? "active" : ""} onClick={() => onCategoryChange(section.category)} key={section.category}>{section.category} <b>{section.count}</b></button>)}</div>
    <div className="automation-layout"><section className="process-grid">{visibleItems.map((event) => <article className="process-card" key={event.id}><div className="process-top"><span className={`route-kind ${event.kind}`}>{resolveProcessIconGlyph(event.icon, event.kind)}</span><div>{changeMap.get(event.id) && <Status tone="warning">{changeMap.get(event.id) === "new" ? "Новый" : "Схема изменена"}</Status>}{event.presentationOverridden && <Status tone="neutral">Настроено</Status>}<Status tone={event.kind === "workflow" ? "violet" : "success"}>{event.kind === "workflow" ? "Workflow" : "Event"}</Status>{event.dangerous && <Status tone="warning">Подтверждение</Status>}</div></div><small className="process-category">{event.category}{event.plugin ? ` · ${event.plugin}` : ""}</small><h3>{event.title}</h3><p>{event.description || "Описание будет загружено из XYOps."}</p>{event.help && <details className="process-help"><summary>Справка по процессу</summary><p>{event.help}</p></details>}<div className="process-meta"><span>{event.fields.length} полей</span><span>{event.targets.length ? `${event.targets.length} targets` : "Targets из XYOps"}</span></div><button className="primary" disabled={!event.enabled || mode === "cached" || !canRun} onClick={() => onLaunch(event)}>{!canRun ? "Недостаточно прав" : mode === "cached" ? "Ожидается подключение XYOps" : "Сформировать и запустить →"}</button></article>)}</section><aside className="runs-panel panel"><div><h3>Последние запуски</h3><small>Постоянный журнал D1</small></div>{recentRuns.length ? recentRuns.slice(0, 6).map((run) => <article key={run.id}><i className={run.status} /><div><strong>{run.title}</strong><small>{formatDateTime(run.startedAt)} · {run.kind}</small><code>{run.jobId}</code></div><RunStatusBadge status={run.status} /></article>) : <div className="runs-empty"><span>◷</span><strong>Запусков пока нет</strong><small>Выберите процесс из каталога</small></div>}</aside></div>
    {!loading && !items.length && <section className="panel catalog-empty"><strong>{error ? "Каталог не загружен" : "Процессы не найдены"}</strong><span>{error || "XYOps вернул пустой каталог либо текущий поиск не нашёл процессов."}</span><div className="empty-actions">{canManageSettings && <button className="secondary" onClick={onOpenSettings}>Открыть настройки</button>}<button className="primary" onClick={onSync}>Повторить синхронизацию</button></div></section>}
  </div>;
}
