"use client";

import { useState } from "react";
import type { FreeIpaAction } from "../../freeipa-ui-events";

export type DirectoryUser = { uid: string; name: string; firstName: string; lastName: string; email: string; groups: number; groupNames: string[]; active: boolean };
export type DirectoryGroup = { name: string; description: string; members: number; memberUids: string[]; type: string };
export type DirectorySource = "demo" | "live" | "unconfigured";

function Status({ children, tone = "success" }: { children: React.ReactNode; tone?: string }) {
  return <span className={`status ${tone}`}>{children}</span>;
}

export function Users({ items, allGroups, total, source, canWrite, canDelete, onCreate, onAction }: { items: DirectoryUser[]; allGroups: DirectoryGroup[]; total: number; source: DirectorySource; canWrite: boolean; canDelete: boolean; onCreate: () => void; onAction: (action: FreeIpaAction) => void }) {
  const [filter, setFilter] = useState<"all" | "active" | "disabled">("all");
  const [selectedUid, setSelectedUid] = useState<string | null>(null);
  const visible = items.filter((user) => filter === "all" || (filter === "active" ? user.active : !user.active));
  const selected = items.find((user) => user.uid === selectedUid) ?? null;
  return <><section className="panel table-panel section-page"><div className="panel-title"><div><h2>Пользователи FreeIPA</h2><p>{`${visible.length} из ${total} учетных записей · ${source === "live" ? "прямое подключение FreeIPA" : source === "demo" ? "демо-данные" : "FreeIPA не настроен"}`}</p></div>{canWrite && <button className="primary" disabled={source === "unconfigured"} onClick={onCreate}>＋ Создать пользователя</button>}</div><div className="filter-row"><button className={`filter ${filter === "all" ? "active-filter" : ""}`} onClick={() => setFilter("all")}>Все</button><button className={`filter ${filter === "active" ? "active-filter" : ""}`} onClick={() => setFilter("active")}>Активные</button><button className={`filter ${filter === "disabled" ? "active-filter" : ""}`} onClick={() => setFilter("disabled")}>Отключённые</button>{!canWrite && <Status tone="neutral">Только просмотр</Status>}</div><div className="data-table"><div className="tr th users-row"><span>Пользователь</span><span>Логин</span><span>Группы</span><span>Статус</span><span>Действия</span></div>{visible.map((u) => <div className="tr users-row" key={u.uid}><span className="person"><b>{u.name.split(" ").map(x => x[0]).join("")}</b><span><strong>{u.name}</strong><small>{u.email}</small></span></span><span className="mono">{u.uid}</span><span>{u.groups}</span><span><Status tone={u.active ? "success" : "neutral"}>{u.active ? "Активен" : "Отключён"}</Status></span><span className="row-actions"><button onClick={() => setSelectedUid(u.uid)}>Карточка</button>{canWrite && <button onClick={() => onAction({ operation: "user_mod", title: `Редактировать ${u.uid}`, preset: { username: u.uid, firstName: u.firstName, lastName: u.lastName, email: u.email } })}>Редактировать</button>}</span></div>)}</div>{source === "unconfigured" && <div className="catalog-empty"><strong>FreeIPA не настроен</strong><span>Сохраните подключение в разделе «Настройки».</span></div>}</section>{selected && <UserDetails user={selected} groups={allGroups} canWrite={canWrite} canDelete={canDelete} close={() => setSelectedUid(null)} action={onAction} />}</>;
}

export function Groups({ items, allUsers, source, canWrite, canDelete, onCreate, onAction }: { items: DirectoryGroup[]; allUsers: DirectoryUser[]; source: DirectorySource; canWrite: boolean; canDelete: boolean; onCreate: () => void; onAction: (action: FreeIpaAction) => void }) {
  const [selectedName, setSelectedName] = useState<string | null>(null);
  const selected = items.find((group) => group.name === selectedName) ?? null;
  return <><div className="content-stack"><div className="page-tools"><div><h2>Группы доступа</h2><p>{`${items.length} групп · ${source === "live" ? "прямое подключение FreeIPA" : source === "demo" ? "демо-данные" : "FreeIPA не настроен"}`}</p></div>{canWrite ? <button className="primary" disabled={source === "unconfigured"} onClick={onCreate}>＋ Создать группу</button> : <Status tone="neutral">Только просмотр</Status>}</div>{source === "unconfigured" ? <section className="panel catalog-empty"><strong>FreeIPA не настроен</strong><span>Сохраните подключение в разделе «Настройки».</span></section> : <section className="group-grid">{items.map((g, i) => <article className="group-card" key={g.name}><div className={`group-avatar c${i % 4}`}>♣</div><h3>{g.name}</h3><p>{g.description}</p><div><span><strong>{g.members}</strong><small>участников</small></span><Status tone="violet">{g.type}</Status></div><div className="group-actions"><button onClick={() => setSelectedName(g.name)}>Открыть группу</button>{canWrite && <button onClick={() => onAction({ operation: "group_add_member", title: `Добавить участника в ${g.name}`, preset: { group: g.name }, choices: { users: allUsers.filter((user) => !g.memberUids.includes(user.uid)).map((user) => user.uid) } })}>＋ Участник</button>}</div></article>)}</section>}</div>{selected && <GroupDetails group={selected} users={allUsers} canWrite={canWrite} canDelete={canDelete} close={() => setSelectedName(null)} action={onAction} />}</>;
}

function UserDetails({ user, groups, canWrite, canDelete, close, action }: { user: DirectoryUser; groups: DirectoryGroup[]; canWrite: boolean; canDelete: boolean; close: () => void; action: (action: FreeIpaAction) => void }) {
  const availableGroups = groups.filter((group) => !user.groupNames.includes(group.name)).map((group) => group.name);
  return <div className="modal-backdrop"><section className="modal identity-modal"><button className="modal-x" onClick={close}>×</button><div className="identity-head"><span>{user.name.split(" ").map((part) => part[0]).join("")}</span><div><small>ПОЛЬЗОВАТЕЛЬ FREEIPA</small><h2>{user.name}</h2><code>{user.uid}</code></div><Status tone={user.active ? "success" : "neutral"}>{user.active ? "Активен" : "Отключён"}</Status></div><div className="identity-facts"><span><small>Email</small><strong>{user.email || "Не указан"}</strong></span><span><small>Группы</small><strong>{user.groups}</strong></span></div><div className="membership-head"><div><h3>Членство в группах</h3><p>{canWrite ? "Изменения применяются напрямую в FreeIPA." : "Доступно только для просмотра."}</p></div>{canWrite && <button className="secondary" disabled={!availableGroups.length} onClick={() => action({ operation: "group_add_member", title: `Добавить ${user.uid} в группу`, preset: { username: user.uid }, choices: { groups: availableGroups } })}>＋ Добавить группу</button>}</div><div className="membership-list">{user.groupNames.map((group) => <span key={group}><b>{group}</b>{canWrite && <button data-portal-confirmation-control="1" aria-label={`Удалить ${user.uid} из ${group}`} onClick={() => action({ operation: "group_remove_member", title: `Удалить ${user.uid} из ${group}`, preset: { username: user.uid, group } })}>×</button>}</span>)}{!user.groupNames.length && <p>Пользователь не входит в группы.</p>}</div><div className="identity-actions">{canWrite && <><button className="secondary" onClick={() => action({ operation: "user_mod", title: `Редактировать ${user.uid}`, preset: { username: user.uid, firstName: user.firstName, lastName: user.lastName, email: user.email } })}>Редактировать</button><button className="secondary" onClick={() => action({ operation: "user_password", title: `Сбросить пароль ${user.uid}`, preset: { username: user.uid } })}>Сбросить пароль</button><button className="secondary" data-portal-confirmation-control={user.active ? "1" : undefined} onClick={() => action({ operation: user.active ? "user_disable" : "user_enable", title: `${user.active ? "Отключить" : "Включить"} ${user.uid}`, preset: { username: user.uid } })}>{user.active ? "Отключить" : "Включить"}</button></>}{canDelete && <button className="danger-button" data-portal-confirmation-control="1" onClick={() => action({ operation: "user_del", title: `Удалить ${user.uid}`, preset: { username: user.uid } })}>Удалить</button>}<button className="secondary" onClick={close}>Закрыть</button></div></section></div>;
}

function GroupDetails({ group, users, canWrite, canDelete, close, action }: { group: DirectoryGroup; users: DirectoryUser[]; canWrite: boolean; canDelete: boolean; close: () => void; action: (action: FreeIpaAction) => void }) {
  const availableUsers = users.filter((user) => !group.memberUids.includes(user.uid)).map((user) => user.uid);
  return <div className="modal-backdrop"><section className="modal identity-modal"><button className="modal-x" onClick={close}>×</button><div className="identity-head"><span>♣</span><div><small>ГРУППА FREEIPA</small><h2>{group.name}</h2><p>{group.description}</p></div><Status tone="violet">{group.type}</Status></div><div className="membership-head"><div><h3>Участники</h3><p>{group.members} пользователей в группе.</p></div>{canWrite && <button className="primary" disabled={!availableUsers.length} onClick={() => action({ operation: "group_add_member", title: `Добавить участника в ${group.name}`, preset: { group: group.name }, choices: { users: availableUsers } })}>＋ Добавить</button>}</div><div className="member-table">{group.memberUids.map((uid) => { const user = users.find((item) => item.uid === uid); return <div key={uid}><span className="person"><b>{(user?.name || uid).split(" ").map((part) => part[0]).join("")}</b><span><strong>{user?.name || uid}</strong><small>{user?.email || uid}</small></span></span><Status tone={user?.active === false ? "neutral" : "success"}>{user?.active === false ? "Отключён" : "Активен"}</Status>{canWrite && <button className="danger-link" data-portal-confirmation-control="1" onClick={() => action({ operation: "group_remove_member", title: `Удалить ${uid} из ${group.name}`, preset: { group: group.name, username: uid } })}>Удалить</button>}</div>; })}{!group.memberUids.length && <p>В группе пока нет участников.</p>}</div><div className="identity-actions">{canDelete && <button className="danger-button" data-portal-confirmation-control="1" onClick={() => action({ operation: "group_del", title: `Удалить группу ${group.name}`, preset: { group: group.name } })}>Удалить группу</button>}<button className="secondary" onClick={close}>Закрыть</button></div></section></div>;
}
