from pathlib import Path

path = Path("scripts/apply-approval-gates-patch.py")
text = path.read_text()
replacements = {
    "'       if (!response.ok) throw new Error(result.error);\\n       await loadRuns(false);\\n       setSelectedProcess(null);\\n       notify(result.mode === \"live\" ? `XYOps запущен: ${result.jobId}` : `Демо-задание создано: ${result.jobId}`);'": "'      if (!response.ok) throw new Error(result.error);\\n      await loadRuns(false);\\n      setSelectedProcess(null);\\n      notify(result.mode === \"live\" ? `XYOps запущен: ${result.jobId}` : `Демо-задание создано: ${result.jobId}`);'",
    "'       if (!response.ok) throw new Error(result.error);\\n       if (result.approvalRequired) { await loadApprovals(); setSelectedProcess(null); navigateTo(\"approvals\"); notify(`Заявка на согласование создана: ${result.approvalId}`); return true; }\\n       await loadRuns(false);\\n       setSelectedProcess(null);\\n       notify(result.mode === \"live\" ? `XYOps запущен: ${result.jobId}` : `Демо-задание создано: ${result.jobId}`);'": "'      if (!response.ok) throw new Error(result.error);\\n      if (result.approvalRequired) { await loadApprovals(); setSelectedProcess(null); navigateTo(\"approvals\"); notify(`Заявка на согласование создана: ${result.approvalId}`); return true; }\\n      await loadRuns(false);\\n      setSelectedProcess(null);\\n      notify(result.mode === \"live\" ? `XYOps запущен: ${result.jobId}` : `Демо-задание создано: ${result.jobId}`);'",
    "'       if (!response.ok) throw new Error(result.error || \"Операция с заданием не выполнена\");\\n       await loadRuns(true);\\n       notify(action === \"cancel\" ? \"Команда остановки отправлена в XYOps\" : `Создан новый запуск: ${result.jobId ?? \"ожидает Job ID\"}`);'": "'      if (!response.ok) throw new Error(result.error || \"Операция с заданием не выполнена\");\\n      await loadRuns(true);\\n      notify(action === \"cancel\" ? \"Команда остановки отправлена в XYOps\" : `Создан новый запуск: ${result.jobId ?? \"ожидает Job ID\"}`);'",
    "'       if (!response.ok) throw new Error(result.error || \"Операция с заданием не выполнена\");\\n       if (result.approvalRequired) { await loadApprovals(); navigateTo(\"approvals\"); notify(`Повторный запуск ожидает согласования: ${result.approvalId}`); return true; }\\n       await loadRuns(true);\\n       notify(action === \"cancel\" ? \"Команда остановки отправлена в XYOps\" : `Создан новый запуск: ${result.jobId ?? \"ожидает Job ID\"}`);'": "'      if (!response.ok) throw new Error(result.error || \"Операция с заданием не выполнена\");\\n      if (result.approvalRequired) { await loadApprovals(); navigateTo(\"approvals\"); notify(`Повторный запуск ожидает согласования: ${result.approvalId}`); return true; }\\n      await loadRuns(true);\\n      notify(action === \"cancel\" ? \"Команда остановки отправлена в XYOps\" : `Создан новый запуск: ${result.jobId ?? \"ожидает Job ID\"}`);'",
}
for old, new in replacements.items():
    if old not in text:
        raise RuntimeError(f"patcher anchor not found: {old[:80]}")
    text = text.replace(old, new, 1)
path.write_text(text)
