export type ConfigurationClass =
  | "production"
  | "development"
  | "recovery"
  | "startup-local"
  | "internal-ephemeral";

export type ConfigurationLifecycle = "startup" | "runtime" | "startup-and-runtime";
export type ConfigurationExposure = "never" | "presence-only" | "bounded-status";
export type ConfigurationCompatibility = "supported" | "legacy" | "internal";

export interface PortalConfigurationRecord {
  name: string;
  class: ConfigurationClass;
  required: boolean;
  secret: boolean;
  lifecycle: ConfigurationLifecycle;
  defaultSemantics: "none" | "documented" | "generated" | "compose-default";
  precedence: string;
  validationOwner: string;
  transportOwner: string;
  exposure: ConfigurationExposure;
  compatibility: ConfigurationCompatibility;
  notes?: string;
}

/**
 * Canonical metadata for operator-supported runtime configuration.
 *
 * This registry deliberately contains metadata only. It must never contain
 * credentials, secret values, parser implementations, or encrypted D1 state.
 * Domain validators, settings lifecycle code, Compose and startup transport
 * remain the owners of their respective behavior.
 */
export const PORTAL_CONFIGURATION_CONTRACT: readonly PortalConfigurationRecord[] = [
  {
    name: "DASHBOARD_PORT",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "none",
    precedence: "environment/deployment",
    validationOwner: "deployment runtime",
    transportOwner: "compose.yaml",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "HOST",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "documented",
    precedence: "environment > start-worker default",
    validationOwner: "scripts/start-worker.mjs",
    transportOwner: "compose.yaml/start-worker",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "PORT",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "documented",
    precedence: "environment > start-worker default",
    validationOwner: "scripts/start-worker.mjs",
    transportOwner: "compose.yaml/start-worker",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "ADMIN_TOKEN",
    class: "production",
    required: false,
    secret: true,
    lifecycle: "startup-and-runtime",
    defaultSemantics: "none",
    precedence: "environment",
    validationOwner: "admin-token runtime policy",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "CONFIG_ENCRYPTION_KEY",
    class: "production",
    required: true,
    secret: true,
    lifecycle: "startup",
    defaultSemantics: "none",
    precedence: "environment > compose required value",
    validationOwner: "scripts/config-encryption-key.mjs",
    transportOwner: "compose.yaml/start-worker",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "DEMO_MODE",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup-and-runtime",
    defaultSemantics: "documented",
    precedence: "environment",
    validationOwner: "runtime demo-mode policy",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "PORTAL_IDENTITY_MODE",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "documented",
    precedence: "environment > identity default",
    validationOwner: "scripts/identity-startup-policy.mjs",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "PORTAL_DEFAULT_ROLE",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "documented",
    precedence: "environment > identity default",
    validationOwner: "scripts/identity-startup-policy.mjs",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "PORTAL_BOOTSTRAP_ADMIN_USERNAME",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "documented",
    precedence: "environment > identity bootstrap default",
    validationOwner: "scripts/identity-startup-policy.mjs",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "PORTAL_BOOTSTRAP_ADMIN_PASSWORD",
    class: "production",
    required: false,
    secret: true,
    lifecycle: "startup",
    defaultSemantics: "none",
    precedence: "environment",
    validationOwner: "scripts/identity-startup-policy.mjs",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "PORTAL_BOOTSTRAP_ADMIN_NAME",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "documented",
    precedence: "environment > identity bootstrap default",
    validationOwner: "scripts/identity-startup-policy.mjs",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "PORTAL_SESSION_TTL_HOURS",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "runtime",
    defaultSemantics: "documented",
    precedence: "environment > identity default",
    validationOwner: "local-auth/session policy",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "IPA_URL",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup-and-runtime",
    defaultSemantics: "none",
    precedence: "environment > persisted integration settings",
    validationOwner: "FreeIPA integration settings",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "IPA_USERNAME",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup-and-runtime",
    defaultSemantics: "none",
    precedence: "environment > persisted integration settings",
    validationOwner: "FreeIPA integration settings",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "IPA_PASSWORD",
    class: "production",
    required: false,
    secret: true,
    lifecycle: "startup-and-runtime",
    defaultSemantics: "none",
    precedence: "environment > persisted integration settings",
    validationOwner: "FreeIPA integration settings",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "IPA_VERIFY_TLS",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup-and-runtime",
    defaultSemantics: "documented",
    precedence: "environment > persisted integration settings",
    validationOwner: "FreeIPA integration settings",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "IPA_GATEWAY_PORT",
    class: "startup-local",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "generated",
    precedence: "environment > ephemeral port allocation",
    validationOwner: "scripts/start-worker.mjs",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "XYOPS_URL",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "startup-and-runtime",
    defaultSemantics: "none",
    precedence: "environment > persisted integration settings",
    validationOwner: "XYOps integration settings",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "XYOPS_API_KEY",
    class: "production",
    required: false,
    secret: true,
    lifecycle: "startup-and-runtime",
    defaultSemantics: "none",
    precedence: "environment > persisted integration settings",
    validationOwner: "XYOps integration settings",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "XYOPS_EVENT_ID",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "runtime",
    defaultSemantics: "none",
    precedence: "environment > persisted integration settings",
    validationOwner: "XYOps integration settings",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "XYOPS_RESULT_FILE_MAX_BYTES",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "runtime",
    defaultSemantics: "documented",
    precedence: "environment > runtime default",
    validationOwner: "XYOps result-file proxy",
    transportOwner: "runtime consumption; forwarding requires explicit evidence",
    exposure: "bounded-status",
    compatibility: "supported",
    notes: "Documented and consumed by runtime code; start-worker forwarding must be verified by a behavior test before changing transport.",
  },
  {
    name: "XYOPS_CATALOG_SYNC_ENABLED",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "runtime",
    defaultSemantics: "documented",
    precedence: "environment > persisted catalog policy",
    validationOwner: "XYOps catalog synchronization",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "XYOPS_CATALOG_SYNC_LOCK_TTL_SECONDS",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "runtime",
    defaultSemantics: "documented",
    precedence: "environment > runtime default",
    validationOwner: "XYOps catalog synchronization",
    transportOwner: "runtime consumption; forwarding requires explicit evidence",
    exposure: "bounded-status",
    compatibility: "supported",
    notes: "Documented and consumed by runtime code; start-worker forwarding must be verified by a behavior test before changing transport.",
  },
  {
    name: "XYOPS_ROUTES_JSON",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "runtime",
    defaultSemantics: "documented",
    precedence: "persisted routes > environment bootstrap routes",
    validationOwner: "XYOps route configuration",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "PORTAL_PROCESS_METADATA_JSON",
    class: "production",
    required: false,
    secret: false,
    lifecycle: "runtime",
    defaultSemantics: "documented",
    precedence: "environment > process metadata default",
    validationOwner: "process presentation metadata",
    transportOwner: "runtime configuration",
    exposure: "bounded-status",
    compatibility: "supported",
  },
  {
    name: "PORTAL_STATIC_IDENTITY",
    class: "development",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "none",
    precedence: "development environment only",
    validationOwner: "development identity policy",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "legacy",
    notes: "Development/static compatibility mode; not the normal production identity model.",
  },
  {
    name: "PORTAL_STATIC_NAME",
    class: "development",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "none",
    precedence: "development environment only",
    validationOwner: "development identity policy",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "legacy",
  },
  {
    name: "PORTAL_RBAC_JSON",
    class: "development",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "none",
    precedence: "development environment only",
    validationOwner: "canonical RBAC policy",
    transportOwner: "scripts/start-worker.mjs",
    exposure: "never",
    compatibility: "legacy",
    notes: "Compatibility surface retained for isolated development/tests; canonical permissions live in portal-permissions.ts.",
  },
  {
    name: "PORTAL_RECOVERY_UID",
    class: "recovery",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "compose-default",
    precedence: "environment > recovery Compose default",
    validationOwner: "recovery Compose profile",
    transportOwner: "compose.yaml",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "PORTAL_RECOVERY_GID",
    class: "recovery",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "compose-default",
    precedence: "environment > recovery Compose default",
    validationOwner: "recovery Compose profile",
    transportOwner: "compose.yaml",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "PORTAL_RECOVERY_DIR",
    class: "recovery",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "compose-default",
    precedence: "environment > recovery Compose default",
    validationOwner: "recovery Compose profile",
    transportOwner: "compose.yaml",
    exposure: "never",
    compatibility: "supported",
  },
  {
    name: "PORTAL_RECOVERY_SECRETS_DIR",
    class: "recovery",
    required: false,
    secret: false,
    lifecycle: "startup",
    defaultSemantics: "compose-default",
    precedence: "environment > recovery Compose default",
    validationOwner: "recovery Compose profile",
    transportOwner: "compose.yaml",
    exposure: "never",
    compatibility: "supported",
  },
] as const;

export function getPortalConfiguration(name: string): PortalConfigurationRecord | undefined {
  return PORTAL_CONFIGURATION_CONTRACT.find((record) => record.name === name);
}
